# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yshi <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/10 16:43:57 by yshi              #+#    #+#              #
#    Updated: 2025/03/10 17:56:42 by yshi             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = ft_display_file
SOURCES = ft_display_file.c
CFLAGS = -Wall -Wextra -Werror

all : $(NAME)

$(NAME) : $(SOURCES)
	cc $(SOURCES) -o $(NAME)

clean :
	rm -rf 
